### ISSUE TITLE
NullPointerException when following the steps in the Quick start doc.

### ISSUE THREAD

**Issue by mando222** [engineblock/engineblock#114]
I ran the commands in the following order.

root@node0:/# mkdir ebdse
root@node0:/# chmod 777 ebdse/
root@node0:/# cd ebdse/
root@node0:/ebdse# curl -O https://raw.githubusercontent.com/engineblock/engineblock/master/eb-cli/bin/run-eb
root@node0:/ebdse# chmod u+x run-eb
root@node0:/ebdse# curl -o eb-cli.jar https://repo1.maven.org/maven2/io/engineblock/eb-cli/1.0.17/eb-cli-1.0.17.jar
root@node0:/ebdse# java -jar eb-cli.jar
root@node0:/ebdse# ./run-eb activity alias=test1 type=diag threads=10 interval=200
Downloading version: 1.0.59
...Download URL: https://repo1.maven.org/maven2/io/engineblock/eb-cli/1.0.59/eb-cli-1.0.59.jar
fetching EngineBlock CLI from https://repo1.maven.org/maven2/io/engineblock/eb-cli/1.0.59/eb-cli-1.0.59.jar...
The EB jar has been saved as eb.jar
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at io.engineblock.core.ScenarioLogger.setLogDir(ScenarioLogger.java:49)
	at io.engineblock.cli.EBCLI.run(EBCLI.java:120)
	at io.engineblock.cli.EBCLI.main(EBCLI.java:33)

**Comment by jshook** [comment]
This was a result of the logging subdir being enabled in a recent release, but with a default logdir of null.
Fixed in latest push to master.
