### ISSUE TITLE
strict rate limiters need redesigned for CO accuracy

### ISSUE THREAD

**Issue by jshook** [engineblock/engineblock#148]
The method of calculation for CO delay was conflicting with the scheduling algorithm in the strict rate limiters. For now, the strict rate limiters will be disabled, and design focus will be given to the average rate limiters. Once the average rate limiters are considered complete, they will be used as the basis for a strict rate limiter implementation with the same suite of tests as a baseline.

**Comment by mbulman** [comment]
@jshook what does "strict" and "average" refer to?  my assumption is strict focuses only on a given second and does not "rollover", whereas average assumes that "50/sec" really means something like "250 every 5 seconds" (over whatever interval).  Do I have that right?

**Comment by jshook** [comment]
You ha e it mostly. The strictest form disallows *any* rate averaging, meaning that if an op was not in the queue ready to be started when the next time slice occurs, that time becomes idle time, never to be reclaimed. This requires strict accounting of time between each op and thus is much harder to do efficiently.

There is a mechanism to allow us to control the behavior between strict and average on a sliding scale, but it did not accurately include C.O. scheduling data in the first implementation. The next implementation should handle both, allow a middle-ground, and accurately report cumulative C.O. scheduling delay per op, as needed for accurate C.O. latencies.

The current average rate limiter should handle C.O. scheduling delay accurately already, with the caveat that it is allowed to burst to catch up to the average target rate.

**Comment by jshook** [comment]
This work has been completed as part of the hybrid rate limiter design. Additional work may be needed for corner-cases in hardware, but that is a different scope of work.
