### ISSUE TITLE
StatementTemplates `format=...` for stdout only work for doc level bindings

### ISSUE THREAD

**Issue by phact** [engineblock/engineblock#183]
https://github.com/engineblock/engineblock/blob/5358b9aabe6e48a5b41af7e3439d1e7a8970e99d/at-stdout/src/main/java/io/engineblock/activitytypes/stdout/StdoutActivity.java#L150

We should support them for bindings at whatever statement and filtering level is provided by the user.

**Comment by jshook** [comment]
This was a result of the order of precedence when configuring the format for a statement. I reversed this so that any time `format=` was specified for stdout, it would override those specified in the yaml.
