### ISSUE TITLE
no main manifest attribute, in eb-cli-2.11.41.jar

### ISSUE THREAD

**Issue by satishrao84** [engineblock/engineblock#191]
> bash-3.2$ java -jar eb-cli-2.11.41.jar 
> no main manifest attribute, in eb-cli-2.11.41.jar
>

What's going on with this? Same problem with all the previous jars

**Comment by jshook** [comment]
The all-in-one jar is packaged simply as `eb-cli.jar` for now.

**Comment by satishrao84** [comment]
Hi Jonathan, 

Where can I find this jar? Do you have the link? 
https://repo1.maven.org/maven2/io/engineblock/eb-cli/2.11.41/ 

Thanks!

**Comment by satishrao84** [comment]
Jonathan, can you please help me with this? :) Where is the eb-cli Jar located?

**Comment by jshook** [comment]
When you build engineblock, it will be in the target directory under the eb-cli module. There is currently no CI to publish the uber jar automatically. 

Can you elaborate a bit on your goals here, or at least let me know what usage pattern you are trying to support? If it is simple CLI usage of the core engineblock features, then this is probably just a CI change to bundle the uber jar with releases.

**Comment by jshook** [comment]
@satishrao84 Giving you an update on this project:
It is being moved to github/nosqlbench/nosqlbench and flattened out with the upstream projects to make it easier for contributors. 

A downstream project called DSBench has binary builds available. It has support for the CQL and stdout activity types. In the near future, the source for those will be shared as well. At least for now, you can get access to a binary which will run on Linux if you need.

I'm sorry for the delay in getting back to you with more specifics. We're working hard to get these projects setup better for more community access.
