### ISSUE TITLE
Scenario wraps user exceptions in runtime exceptions

### ISSUE THREAD

**Issue by phact** [engineblock/engineblock#193]
We should keep the exception type to clean up logging downstream.

https://github.com/engineblock/engineblock/blob/master/eb-core/src/main/java/io/engineblock/core/ActivityExecutor.java#L97

**Comment by jshook** [comment]
@phact Can you elaborate on this a bit?

**Comment by jshook** [comment]
superseded by https://github.com/nosqlbench/nosqlbench/issues/11
