### ISSUE TITLE
Wrong activity type should be a User Exception

### ISSUE THREAD

**Issue by phact** [engineblock/engineblock#194]
https://github.com/engineblock/engineblock/blob/master/eb-api/src/main/java/io/engineblock/util/SimpleServiceLoader.java#L46

**Comment by phact** [comment]
Which is not that simple because eb-util doesn't import eb-core. This promises to become a major problem with dependencies. Why don't we use an Exception from java.lang like `UnsupportedOperationException`?

**Comment by jshook** [comment]
I've logged this in the new consolidated project as https://github.com/nosqlbench/nosqlbench/issues/3, and added details on implementation that should clarify how to deal with the dependency issues.
