### ISSUE TITLE
Add the ability to write histogram intervals to a log via HistogramLogWriter

### ISSUE THREAD

**Issue by tjake** [engineblock/engineblock#89]
In cassandra-stress the hdr histogram is written to a logfile (code here)[https://github.com/apache/cassandra/blob/cfa90c065f649ea5fac5507cf6c06c9a3d3254de/tools/stress/src/org/apache/cassandra/stress/report/StressMetrics.java#L86]

This allows you to generate the typical hdr histogram output seen on hdrhistogram.org for their latency graphing tool as well as the ability to aggregate and track throughput numbers across many runs.

This format also supports tags so you can have different histograms tracked in the same file (which would map well to your aliases)

**Comment by jshook** [comment]
My proposal for how to control this would look something like this:

- Provide a global config option that lets you turn on histogram logging, like "--loghistograms '.*:targetfile',
where the format '<pattern>:<filename>' determines which histograms get logged.
- If the config value is in '<filename>' format (no regex), then all histograms are hooked for that logfile.
- When a histogram is registered through the internal API, for each matching config, create a logger for it if needed, and indicate such in the info level standard logging.
- Globally track the loggers in the JVM without discarding them. This means that multiple activites or scripts within the same scenario will be able to target the same active log.

@tjake does this look reasonble to you?

**Comment by jshook** [comment]
This has been implemented in the latest PR
I'll add some updated docs to go with it.

To use:

*to log all compatible metrics:*
~~~
--log-histograms alogfilename
~~~

* to log only some metrics:*
~~~
--log-histograms '.*suffixmatch:alogfilename'
~~~

Also, you can specify the option multiple times, and a metric can participate in multiple logs.

Oh, I just realized as well, that the tagging is not included. I'll add that and push an update soon.

**Comment by jshook** [comment]
tag added to latest commit before publishing 1.0.36

**Comment by jshook** [comment]
To be clear, this is in 1.0.36, which will be included in downstream artifacts shortly.

**Comment by jshook** [comment]
There was a silly switch/CLI bug in 1.0.36. I've verified that this feature works fine in a newer version that is on its way to Maven central.
