### ISSUE TITLE
HistogramLogWriter not updating interval start and end

### ISSUE THREAD

**Issue by tjake** [engineblock/engineblock#93]
In the code from #89 I think there is a problem here:

https://github.com/engineblock/engineblock/blob/e8c518f5acc2fd5b2407286ca63d8f11e9e9c73e/eb-api/src/main/java/io/engineblock/metrics/DeltaHdrHistogramReservoir.java#L102

The histogram needs to have its start and end interval set otherwise the writer is wrong.

So this should include:
delta.setStartTimestamp(...)
delta.setEndTimestamp(...)

**Comment by jshook** [comment]
@tjake I've added the missing setters and a test for this. I'll push publish and bump downstream artifacts tonight.

**Comment by jshook** [comment]
Not sure why it was closed before I merged the fix, though.
